title: "Grant Morfitt Wiki"
remote_theme: pages-themes/minimal@latest
plugins:
  - jekyll-remote-theme
markdown: kramdown
highlighter: rouge
include:
  - wiki
kramdown:
  syntax_highlighter: rouge

